name: calliope-res-margins
channels:
    - conda-forge
    - default
dependencies:
    - python=3.7
    - calliope=0.6.11
    - pip:
        - git+https://github.com/FraSanvit/calliope.git@0.6-reserves-margins-fix